// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbqqqsfbuaqjnifqsklg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJicXFxc2ZidWFxam5pZnFza2xnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNzU4MDMsImV4cCI6MjA2MDY1MTgwM30.a987GkZULH-VweLaooxEsmL0D4eF0VZVDtH2sgNklFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);