// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://letztvhtfmngrhbqrbng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxldHp0dmh0Zm1uZ3JoYnFyYm5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NTQ2MDksImV4cCI6MjA2MTIzMDYwOX0.vYLMweArNZvLoDtHffGcSgmFAC4kQcdZL2pRpW00n1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);