// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phofdpcnmjikjrocvjaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBob2ZkcGNubWppa2pyb2N2amF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0ODg2NzMsImV4cCI6MjA2MTA2NDY3M30.NQL4IgzWEjyjlQu6i5otAmJv_8tNf0X_rwLz63-SLV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);